"use client";
import {useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
type Mode="ingresar"|"registro"|"recuperar";
export default function LiteAuthForm({mode}:{mode:Mode}){
const router=useRouter();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [nombre,setNombre]=useState("");const [role,setRole]=useState("productor");const [terms,setTerms]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const supabase=createClient();if(mode==="ingresar"){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;router.replace("/lite/perfil");router.refresh()}else if(mode==="registro"){if(!terms)throw new Error("Aceptá los términos y condiciones para registrarte.");const {data,error}=await supabase.auth.signUp({email,password,options:{data:{nombre,tipo:role,country_code:"AR",terms_accepted_at:new Date().toISOString(),terms_version:"2026-09-23"},emailRedirectTo:window.location.origin+"/auth/callback?next=/lite/perfil"}});if(error)throw error;setMessage(data.session?"Cuenta creada. Ya podés entrar.":"Revisá tu correo y confirmá tu cuenta para ingresar.")}else{const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+"/auth/callback?next=/lite/cuenta/nueva-clave"});if(error)throw error;setMessage("Si existe una cuenta con ese correo, vas a recibir un enlace para recuperar tu contraseña.")}}catch(err){setError(err instanceof Error?err.message:"No se pudo completar la operación.")}finally{setBusy(false)}}
const inputStyle={padding:"15px",fontSize:16,border:"1px solid #ccc",borderRadius:10,width:"100%",boxSizing:"border-box" as const};
return <form onSubmit={submit} style={{display:"grid",gap:15,marginTop:25}}>{mode==="registro"&&<><label>Nombre<input required style={inputStyle} value={nombre} onChange={e=>setNombre(e.target.value)} autoComplete="name"/></label><label>Perfil<select style={inputStyle} value={role} onChange={e=>setRole(e.target.value)}><option value="productor">Productor</option><option value="propietario">Propietario</option><option value="prestador">Prestador rural</option></select></label></>}<label>Correo electrónico<input required type="email" autoComplete="email" style={inputStyle} value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode!=="recuperar"&&<label>Contraseña<input required type="password" minLength={6} autoComplete={mode==="registro"?"new-password":"current-password"} style={inputStyle} value={password} onChange={e=>setPassword(e.target.value)}/></label>}{mode==="registro"&&<label style={{fontSize:14}}><input type="checkbox" required checked={terms} onChange={e=>setTerms(e.target.checked)}/> Acepto los <Link href="/terminos" target="_blank">términos y condiciones</Link></label>}{error&&<p role="alert" style={{color:"#9b2226"}}>{error}</p>}{message&&<p role="status">{message}</p>}<button disabled={busy} style={{background:"#1d1d1d",color:"#fff",padding:17,border:0,borderRadius:12,fontSize:17}}>{busy?"Procesando...":mode==="ingresar"?"Ingresar":mode==="registro"?"Crear cuenta":"Enviar enlace"}</button><Link href="/lite/cuenta/ingresar">Ingresar</Link><Link href="/lite/cuenta/registro">Crear usuario</Link><Link href="/lite/cuenta/recuperar">Olvidé mi contraseña</Link></form>
}