"use client";
import {useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
type Mode="ingresar"|"registro"|"recuperar";
const field:React.CSSProperties={width:"100%",padding:"15px 14px",border:"1px solid #ccc",borderRadius:12,fontSize:16,boxSizing:"border-box",background:"white",color:"#222"};
export default function LiteAuth({mode}:{mode:Mode}){
const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [nombre,setNombre]=useState("");const [tipo,setTipo]=useState<"productor"|"propietario"|"prestador">("productor");const [terms,setTerms]=useState(false);const [loading,setLoading]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const router=useRouter();
async function submit(e:React.FormEvent){e.preventDefault();setError("");setMessage("");setLoading(true);try{const supabase=createClient();if(mode==="ingresar"){const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;router.push("/lite/perfil");router.refresh();}
else if(mode==="recuperar"){const redirectTo=window.location.origin+"/auth/confirm?next="+encodeURIComponent("/auth/reset-password");const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo});if(error)throw error;setMessage("Te enviamos un enlace de recuperación. Revisá tu correo y spam.");}
else{if(password.length<6)throw new Error("La contraseña debe tener al menos 6 caracteres.");if(!terms)throw new Error("Aceptá los términos y condiciones.");const {data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:window.location.origin+"/auth/callback",data:{nombre,tipo,country_code:"AR",terms_accepted_at:new Date().toISOString(),terms_version:"2026-09-23"}}});if(error)throw error;if(data.user?.identities?.length===0){setError("La cuenta ya existe. Probá ingresar o recuperar tu contraseña.");}else{setMessage("Revisá tu email para confirmar tu cuenta antes de ingresar.");}}}catch(err){setError(err instanceof Error?err.message:"No pudimos completar la operación.");}finally{setLoading(false)}}
return <div style={{maxWidth:460,margin:"0 auto",padding:"28px 22px 115px",fontFamily:"Arial,sans-serif",color:"#222"}}><Link href="/lite/perfil" style={{textDecoration:"none",color:"#333"}}>← Mi perfil</Link><h1 style={{fontSize:34,letterSpacing:-1.4,marginTop:32}}>{mode==="ingresar"?"Ingresar":mode==="registro"?"Crear cuenta":"Recuperar contraseña"}</h1><p style={{color:"#777",lineHeight:1.5}}>Tu cuenta es la misma de RentoCampo.</p><form onSubmit={submit} style={{display:"grid",gap:14,marginTop:26}}>
{mode==="registro"&&<><label>Nombre<input required value={nombre} onChange={e=>setNombre(e.target.value)} style={{...field,marginTop:7}}/></label><label>Soy...<select value={tipo} onChange={e=>setTipo(e.target.value as typeof tipo)} style={{...field,marginTop:7}}><option value="productor">Productor</option><option value="propietario">Propietario</option><option value="prestador">Servicios rurales</option></select></label></>}
<label>Email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} style={{...field,marginTop:7}}/></label>
{mode!=="recuperar"&&<label>Contraseña<input type="password" required minLength={mode==="registro"?6:undefined} autoComplete={mode==="registro"?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)} style={{...field,marginTop:7}}/></label>}
{mode==="registro"&&<label style={{fontSize:13,lineHeight:1.5}}><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/> Acepto los <Link href="/terminos" target="_blank">términos y condiciones</Link>.</label>}
{error&&<p role="alert" style={{color:"#a22",fontSize:14}}>{error}</p>}{message&&<p role="status" style={{fontSize:14}}>{message}</p>}
<button type="submit" disabled={loading} style={{...field,background:"#202020",color:"white",fontWeight:700,cursor:"pointer"}}>{loading?"Procesando...":mode==="ingresar"?"Ingresar":mode==="registro"?"Registrarme":"Enviar enlace"}</button></form><div style={{display:"grid",gap:14,marginTop:28,fontSize:14}}><Link href="/lite/cuenta/ingresar">Ya tengo cuenta</Link><Link href="/lite/cuenta/registro">Registrarme gratis</Link><Link href="/lite/cuenta/recuperar">Olvidé mi contraseña</Link></div></div>}
